### ISSUE TITLE
Crash when missing location information

### ISSUE THREAD

**Issue by sebszocinski** [jimblue/statamic-addon-instagram-hub#3]
If a media doesn't have any `location` information we get an undefined index of name on line 47: `$media[$key]['location'] = $val['location']['name'];`

Temp solution for me was to just comment out those three lines from 47-49:

```
$media[$key]['location'] = $val['location']['name'];
$media[$key]['location_latitude'] = $val['location']['latitude'];
$media[$key]['location_longitude'] = $val['location']['longitude'];
```

But there should probably be a better fix for this as it seems the location fields are optional?? i'll leave it to you to work out.

**Comment by jimblue** [comment]
Hey @sebszocinski,
Thank you for reporting this issue.
It's fixed since the latest version release two months ago (sorry I forget to answer you)

Cheeres
